language: python
dist: xenial
sudo: required
cache: pip
python: 3.7
before_install:
  - pip install psycopg2
  - pip install mypy
  - pip install flake8
  - pip install flake8-builtins
  - pip install flake8-import-order
  - pip install flake8-quotes
script:
  - make flake8
  - make mypy
